<?php

namespace Splicewire\Beam\Frame;

use Illuminate\Contracts\Foundation\Application;

/**
 * The build-time cache of discovered `#[AdminResource]` class-strings — beam's mirror of Laravel's
 * `bootstrap/cache/packages.php` package-discovery manifest.
 *
 * The PER-BOOT filesystem walk (`AttributedClassScanner` over the configured discover-paths) is the
 * dev fallback; in production a host runs `splicewire:beam:frame-cache` once at deploy, which writes the resolved
 * class-string list here. At boot {@see BeamServiceProvider::discoverResources()} reads this manifest
 * when present (fast path — no `Finder` walk, just `registerClass()` per cached FQCN) and only falls
 * back to a live scan when it is absent. The explicit `resources.classes` list is always honoured on
 * top, cache or no cache (it is cheap).
 *
 * The file is a plain `return [...]` PHP array of class-strings, opcache-friendly like `packages.php`.
 */
class FrameResourceManifest
{
    public function __construct(private Application $app) {}

    /** Absolute path to the cached manifest, alongside Laravel's own bootstrap-cache manifests. */
    public function path(): string
    {
        return $this->app->bootstrapPath('cache/beam-frame-resources.php');
    }

    public function exists(): bool
    {
        return is_file($this->path());
    }

    /**
     * Read the cached class-string list. Returns null when the cache is absent (the signal to fall
     * back to a live scan) and [] when it is present-but-empty.
     *
     * @return list<class-string>|null
     */
    public function read(): ?array
    {
        if (! $this->exists()) {
            return null;
        }

        $classes = require $this->path();

        return is_array($classes) ? array_values($classes) : [];
    }

    /**
     * Write the resolved class-string list as an opcache-friendly `return [...]` PHP file.
     *
     * @param  array<int, class-string>  $classes
     */
    public function write(array $classes): void
    {
        $classes = array_values(array_unique($classes));

        $exported = array_map(
            static fn (string $class): string => '    '.var_export($class, true).',',
            $classes,
        );

        $body = "<?php\n\n// Generated by `splicewire:beam:frame-cache` — do not edit. Delete via `splicewire:beam:frame-clear`.\n\nreturn [\n"
            .implode("\n", $exported)
            .($exported === [] ? '' : "\n")
            ."];\n";

        @mkdir(dirname($this->path()), 0755, true);

        file_put_contents($this->path(), $body);
    }

    /** Remove the cached manifest (dev / `splicewire:beam:frame-clear` / `optimize:clear`). */
    public function clear(): void
    {
        if ($this->exists()) {
            @unlink($this->path());
        }
    }
}
